### ISSUE TITLE
Added reasons for your findings would be very helpful

### ISSUE THREAD

**Issue by gugl** [planningcenter/react-patterns#27]
Thanks a lot for writing your experiences and findings down. While reading some of your best practices like https://github.com/planningcenter/react-patterns#view-components I wondered what the reasons for your decisions are. Would be really helpful.

Thanks

**Comment by chantastic** [comment]
Thanks!

The biggest reason that's important (for us) is to maximize reusability of components. When you build layout opinions into your components, you limit them pretty dramatically. On the flip side, you can pretty quickly run up your component count by creating a bunch of layout-wrapped components. By creating reusable layout components that take you can compose around domain components, you have the ability to reuse either in different contexts.

More importantly, it gives you control over owner/ownee relationship and performance optimization...

In the example given, you could spec `BSRow` with `shouldComponentUpdate () { return false }` and guarantee that the your static layout component never become a performance bottleneck.

Likewise, you don't have to string props through your layout-components. In the "bad" example, your intermediate component becomes a pass-through for props. In the "good" example, you have better control over the owner/ownee relationship. Here's an example:

```js
MyComponent extends React.Component {
  constructor () {
    super(props);
    this.handleClick = () => { /* do stuff from the owner */ }
  }
  render () {
    return <div>
      <BSRow>
        <button type="button" onClick={this.handleClick}> click me </button>
      </BSRow>
    </div>
  }
}
```

`BSRow` could be there or not and it makes no difference.

---

Sorry that's kinda a quick and dirty explanation. If it's still fuzzy, let me know :)

**Comment by gugl** [comment]
Wow. thanks for the quick and long answer. That makes totally sense now. On the other side, as you said, it can quickly become a long list of layout components. I guess it makes sense to carefully create your own standard set of configureable layout components to keep them under control.

Another question, when you are so kind, could you give me some more insight in the ES2015 vs coffeescript topic? I'm pretty comfortable with coffeescript. Can you give me an example of a problem you had? And do you see any downside of using ES2015?

Thanks so much.

**Comment by chantastic** [comment]
Totally, one way to combat an overwhelming number of layout components is to add a little bit of configuration to the layout components themselves. For example, you could get away with having a single `BSCol` component that took props to configure the number of columns each instance took up.

On JavaScript vs CoffeeScript: I think we're still conditioned to think of JavaScript as what the browser supports natively, today. But as of a couple months ago, ES2015 **is** JavaScript. The APIs you invest in learning are a standard. The argument does get murky though, given that you're transforming code anyway and and you could be writing literally any language and target ES5 JavaScript.

For our team, CoffeeeScript broke down as we moved more toward JSX. CoffeeScript doesn't play very nicely with JSX. Your options are:

A. Avoid JSX, use `React.createElement` or `React.DOM`
B. Use CJSX

A isn't great because the React team often uses JSX to absorb API changes to React. This was particularly painful in the transition from 0.12 to 0.13 when ES2015 class support was introduced. But it's made a couple changes difficult. You also don't get things like `displayName` for free.

B is sketchy because you're hinging development on the maintenance of a 3rd party project. Some people swear by it. I don't like it. Maintainers burn out and I don't want to be stuck in a position where we have to either take up maintenance of a CoffeeScript transformer or re-write our codebase.

The React community has pretty much rallied around Babel. Babel is now what React uses to transform React source to ES5. The fact that Babel is so closely tied to React source gives me some nice assurances about the stability of stack. I'm able to take advantage of every feature the announce right away. Because of this almost all the example code you'll see in blogposts is ES2015.

As far as syntax goes, it's gained a lot from CoffeeScript. I think you'll be pleasantly surprised at how easy the transition is. As a Coffee to ES2015 convert, I can't think of a single reason to go back to CoffeeScript... well comprehensions were pretty nice :)

**Comment by gugl** [comment]
Thanks again.

At the moment I'm using file_name.js.jsx.coffee files using react-rails and using backticks for the JSX part. Do you have bad experience with this way as well?

**Comment by gugl** [comment]
Sorry. Forgot the gist for the comment above. :) 
https://gist.github.com/gugl/cc0cf2983de47def471b

**Comment by gugl** [comment]
Ok. Don't worry. Now that I tried your style with ES2015 it makes a lot of sense and your recommended best practices already start to make a lot of sense as well. :) Thank you so much for sharing your insight!

**Comment by chantastic** [comment]
@gugl Awesome! I'm so glad this was helpful for you. Feel free to hit us up any time. These obviously aren't infallible recommendations. So, if something seems funky let us know. We love learning :)
